## Tkinter ile arayüz oluşturma

In [114]:
#Kütüphanelerin indiirilmesi:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import tkinter as tk

#Veri setini indiriyoruz:
veri= pd.read_excel("https://www.dropbox.com/s/luoopt5biecb04g/SATILK_EV1.xlsx?dl=1",index_col=0)
veri.head()

   Fiyat  Oda_Sayısı  Net_m2  Katı  Yaşı
0    475           1      40     0     6
1    475           1      55     0     5
2    450           1      50     0     7
3    450           1      55     1     6
4    475           1      45     2     7

In [115]:
# Hedef (y) ve öznitelik değişkenlerini (x) tanımlayalım:
x=veri[["Oda_Sayısı","Net_m2","Katı","Yaşı"]]
y=veri["Fiyat"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [116]:
#Algoritmayı eğitip eğitim verisi üzerinden model oluşturmasını sağlayalım:
model=LinearRegression()
model.fit(x_train,y_train)

print("Intercept: \n",model.intercept_)
print("Coefficients: \n",model.coef_)
coeff_df=pd.DataFrame(model.coef_,x.columns,columns=["Öznitelik_Katsayıları"])
coeff_df

Intercept:
 305.16258952877524
Coefficients:
 [118.35066956   1.13309207   7.09688622  -4.66570638]

            Öznitelik_Katsayıları
Oda_Sayısı             118.350670
Net_m2                   1.133092
Katı                     7.096886
Yaşı                    -4.665706

## TKINTER GUI

In [123]:
root=tk.Tk()

canvas1=tk.Canvas(root,width=400,height=400)
canvas1.pack()

label1=tk.Label(root,text="Oda_Sayısı: ")
canvas1.create_window(100,100,window=label1)
entry1=tk.Entry(root)
canvas1.create_window(200,100,window=entry1)

label2=tk.Label(root,text="Net_m2: ")
canvas1.create_window(90,120,window=label2)
entry2=tk.Entry(root)
canvas1.create_window(200,120,window=entry2)

label3=tk.Label(root,text="Katı: ")
canvas1.create_window(80,140,window=label3)
entry3=tk.Entry(root)
canvas1.create_window(200,140,window=entry3)

label4=tk.Label(root,text="Yaşı: ")
canvas1.create_window(80,160,window=label4)
entry4=tk.Entry(root)
canvas1.create_window(200,160,window=entry4)

def values():
    global Oda_Sayısı,Net_m2,Katı,Yaşı
    Oda_Sayısı=float(entry1.get())
    Net_m2=float(entry2.get())
    Katı=float(entry3.get())
    Yaşı=float(entry4.get())

    prediction_result=("Evin tahmin edilen fiyatı :" ,1000*int(model.predict([[Oda_Sayısı,Net_m2,Katı,Yaşı]])))
    label_prediction=tk.Label(root,text=prediction_result,bg="lawngreen")
    canvas1.create_window(200,220,window=label_prediction)

button1=tk.Button(root,text="Evin tahminFiyatını Hesapla",command=values,bg="orange")
canvas1.create_window(200,190,window=button1)

root.mainloop()