## Tkinter ile arayüz oluşturma

In [7]:
#Kütüphanelerin indiirilmesi:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import tkinter as tk

#Veri setini indiriyoruz:
veri= pd.read_excel("https://www.dropbox.com/s/luoopt5biecb04g/SATILK_EV1.xlsx?dl=1",index_col=0)
veri.head()

   Fiyat  Oda_Sayısı  Net_m2  Katı  Yaşı
0    475           1      40     0     6
1    475           1      55     0     5
2    450           1      50     0     7
3    450           1      55     1     6
4    475           1      45     2     7

In [11]:
# Hedef (y) ve öznitelik değişkenlerini (x) tanımlayalım:
x=veri[["Oda_Sayısı","Net_m2","Katı","Yaşı"]]
y=veri["Fiyat"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
#Algoritmayı eğitip eğitim verisi üzerinden model oluşturmasını sağlayalım:
model=LinearRegression()
model.fit(x_train,y_train)

print("Intercept: \n",model.intercept_)
print("Coefficients: \n",model.coef_)
coeff_df=pd.DataFrame(model.coef_,x.columns,columns=["Öznitelik_Katsayıları"])
coeff_df

Intercept:
 305.16258952877524
Coefficients:
 [118.35066956   1.13309207   7.09688622  -4.66570638]

            Öznitelik_Katsayıları
Oda_Sayısı             118.350670
Net_m2                   1.133092
Katı                     7.096886
Yaşı                    -4.665706